import { KrakenClient } from "./kraken.js";
import { runBacktest } from "./backtest.js";

const client = new KrakenClient();
const button = document.getElementById("runBacktest");
const cancel = document.getElementById("cancelBacktest");
const bar = document.getElementById("backtestProgressBar");
const text = document.getElementById("backtestProgressText");
const box = document.getElementById("backtestProgress");
const results = document.getElementById("backtestResults");
let cancelled = false;
const esc=(v)=>String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;");
const fmt=(v,d=2)=>Number.isFinite(Number(v))?Number(v).toLocaleString("nl-NL",{minimumFractionDigits:d,maximumFractionDigits:d}):"—";
function progress(p,label){if(box)box.hidden=false;if(bar)bar.style.width=`${p}%`;if(text)text.textContent=label;}
function selectedSymbol(){return document.getElementById("chartMarketSelect")?.value||"PF_XBTUSD";}
function render(result,label,friction){const s=result.summary,pf=s.profitFactor===Infinity?"∞":fmt(s.profitFactor);results.innerHTML=`<h4>${esc(label)} · 90 dagen</h4><div class="result-grid"><div><span>Setups</span><strong>${s.total}</strong></div><div><span>Winst / verlies / time-out</span><strong>${s.wins} / ${s.losses} / ${s.timeouts}</strong></div><div><span>Winrate</span><strong>${fmt(s.winRate)}%</strong></div><div><span>Gemiddelde R</span><strong>${fmt(s.averageR)}R</strong></div><div><span>Profit factor</span><strong>${pf}</strong></div><div><span>Max drawdown</span><strong>${fmt(s.maxDrawdownR)}R</strong></div></div><p class="${s.sufficientSample?"result-note":"sample-warning"}">${s.sufficientSample?"Minimaal twintig trades in de steekproef; resultaten uit het verleden geven geen garantie.":"Onvoldoende steekproef: minder dan twintig trades."}</p><p class="${friction?"result-note":"sample-warning"}">${friction?"Historische funding en spread zijn meegenomen.":"Gedeeltelijke marktfrictiedata: Kraken leverde funding en/of spread niet volledig. Candles en 85+-gates zijn wel volledig doorgerekend."}</p>`;}
async function execute(event){event.preventDefault();event.stopImmediatePropagation();if(button.disabled)return;cancelled=false;button.disabled=true;if(cancel)cancel.hidden=false;const symbol=selectedSymbol();try{progress(5,`${symbol}: 1u-history voorbereiden…`);const oneHour=await client.getHistory(symbol,"60",95,{onProgress:(done,total,cached)=>progress(5+Math.round(done/total*30),`${symbol}: 1u ${cached?"uit cache":`blok ${done}/${total}`}`)});if(cancelled)return;progress(38,"4u-context in blokken laden…");const fourHour=await client.getHistory(symbol,"240",150,{onProgress:(done,total,cached)=>progress(38+Math.round(done/total*18),`4u ${cached?"uit cache":`blok ${done}/${total}`}`)});if(cancelled)return;progress(58,"1d-context in blokken laden…");const daily=await client.getHistory(symbol,"D",180,{onProgress:(done,total,cached)=>progress(58+Math.round(done/total*10),`1d ${cached?"uit cache":`blok ${done}/${total}`}`)});if(cancelled)return;progress(70,"Funding en spread ophalen…");const [funding,spread]=await Promise.allSettled([client.getFundingHistory(symbol),client.getSpreadHistory(symbol)]);if(cancelled)return;const fundingSeries=funding.status==="fulfilled"?funding.value:[],spreadSeries=spread.status==="fulfilled"?spread.value:[],friction=funding.status==="fulfilled"&&spread.status==="fulfilled";progress(84,"85+ A/A+ setups zonder vooruitkijken doorrekenen…");const instruments=await client.getInstruments();const market=instruments.find(m=>m.symbol===symbol)||{symbol,label:symbol,tradeable:true,maxLeverage:4};await new Promise(r=>setTimeout(r,0));const result=runBacktest({symbol,candlesByTimeframe:{"60":oneHour,"240":fourHour,D:daily},instrument:market,fundingSeries,spreadSeries});render(result,market.label||symbol,friction);progress(100,"Backtest afgerond.");}catch(error){results.innerHTML=`<p class="sample-warning">Backtest mislukt bij de historische datalaag: ${esc(error.message)}.</p>`;progress(0,"Backtest gestopt.");}finally{button.disabled=false;if(cancel)cancel.hidden=true;cancelled=false;}}
button?.addEventListener("click",execute,{capture:true});
cancel?.addEventListener("click",()=>{cancelled=true;if(text)text.textContent="Stoppen na het huidige datablock…";},{capture:true});
