import { TIMEFRAMES, TRADE_DEFAULTS } from "./constants.js";
import { analyzeMarket } from "./signals.js";
import { passes85TradeGate } from "./trade-universe.js";

export const BACKTEST_MIN_SCORE = 85;
export const BACKTEST_QUALITIES = Object.freeze(new Set(["A", "A+"]));

function candlesClosedBy(candles, intervalMs, timestamp) { return candles.filter((candle) => candle.start + intervalMs <= timestamp); }
function calculateSummary(trades) { const wins=trades.filter(t=>t.netR>0).length,losses=trades.filter(t=>t.netR<0).length,timeouts=trades.filter(t=>t.outcome==="timeout").length,positive=trades.filter(t=>t.netR>0).reduce((s,t)=>s+t.netR,0),negative=Math.abs(trades.filter(t=>t.netR<0).reduce((s,t)=>s+t.netR,0));let streak=0,maxStreak=0,equity=0,peak=0,maxDrawdownR=0;for(const trade of trades){if(trade.netR<0){streak++;maxStreak=Math.max(maxStreak,streak);}else streak=0;equity+=trade.netR;peak=Math.max(peak,equity);maxDrawdownR=Math.max(maxDrawdownR,peak-equity);}return{total:trades.length,wins,losses,timeouts,winRate:trades.length?wins/trades.length*100:0,averageR:trades.length?trades.reduce((s,t)=>s+t.netR,0)/trades.length:0,expectancyR:trades.length?trades.reduce((s,t)=>s+t.netR,0)/trades.length:0,profitFactor:negative>0?positive/negative:positive>0?Infinity:0,maxLosingStreak:maxStreak,maxDrawdownR,sufficientSample:trades.length>=20,minScore:BACKTEST_MIN_SCORE,qualities:[...BACKTEST_QUALITIES]};}
function levelHit(c,d,l,k){if(d===1)return k==="stop"?c.low<=l:c.high>=l;return k==="stop"?c.high>=l:c.low<=l;}
export function evaluateTradeWindow({candles,startIndex,direction,entry,stop,target1,target2,maxHold=24,target1Fraction=.5}){const risk=Math.abs(entry-stop);if(!(risk>0))return{outcome:"invalid",grossR:0,exitIndex:startIndex,stop,target1,target2,target1Hit:false,target2Hit:false};const t1R=direction*(target1-entry)/risk,t2R=direction*(target2-entry)/risk;let remaining=1,grossR=0,target1Hit=false,target2Hit=false,outcome="timeout",exitIndex=Math.min(startIndex+maxHold-1,candles.length-1);for(let i=startIndex;i<=exitIndex;i++){const c=candles[i],stopHit=levelHit(c,direction,stop,"stop"),t1=!target1Hit&&levelHit(c,direction,target1,"target"),t2=levelHit(c,direction,target2,"target");if(!target1Hit){if(stopHit){grossR-=remaining;outcome="loss";exitIndex=i;remaining=0;break;}if(t1){target1Hit=true;const closed=Math.min(target1Fraction,remaining);grossR+=closed*t1R;remaining-=closed;}}if(remaining>0&&target1Hit){if(stopHit){grossR-=remaining;outcome=grossR>0?"partial-win":"loss";exitIndex=i;remaining=0;break;}if(t2){target2Hit=true;grossR+=remaining*t2R;remaining=0;outcome="win";exitIndex=i;break;}}if(i===exitIndex&&remaining>0){grossR+=remaining*direction*(c.close-entry)/risk;outcome=target1Hit?"partial-timeout":"timeout";remaining=0;}}return{outcome,grossR,exitIndex,stop,target1,target2,target1Hit,target2Hit};}
function valueAt(series,timestamp,fallback=0){let value=fallback;for(const row of series||[]){if(row.start>timestamp)break;if(Number.isFinite(Number(row.value)))value=Number(row.value);}return value;}
function fundingBetween(series,from,to){return(series||[]).filter(row=>row.start>=from&&row.start<=to).reduce((sum,row)=>sum+(Number(row.value)||0),0);}
function analyzeAt({symbol,history,price,spreadPct,fundingRate,instrument}){const spread=price*spreadPct/100;return analyzeMarket({symbol,candlesByTimeframe:history,ticker:{lastPrice:price,bid:price-spread/2,ask:price+spread/2,markPrice:price,indexPrice:price,premiumPct:0,fundingRate,fundingRatePrediction:fundingRate,volumeQuote:1_000_000,serverTime:history["60"].at(-1).start+TIMEFRAMES["60"].milliseconds,bookValidated:true,buySlippagePct:spreadPct/2,sellSlippagePct:spreadPct/2,bookDepthMultiple:10,validatedDepthUSD:1_000_000},instrument,turnoverQuality:.75,dataAgeMs:0});}

export function runBacktest({symbol,candlesByTimeframe,instrument={tradeable:true,maxLeverage:4},spreadSeries=[],fundingSeries=[],defaultSpreadPct=.05,takerFeePct=TRADE_DEFAULTS.takerFeeRatePerSide*100,startAt=Date.now()-90*24*60*60*1000,btcCandlesByTimeframe=null,btcInstrument={tradeable:true,maxLeverage:4}}){const oneHour=candlesByTimeframe["60"]||[],fourHour=candlesByTimeframe["240"]||[],daily=candlesByTimeframe.D||[],trades=[];for(let index=55;index<oneHour.length-1;index++){const decision=oneHour[index],decisionTime=decision.start+TIMEFRAMES["60"].milliseconds;if(decisionTime<startAt)continue;const history={"60":oneHour.slice(0,index+1),"240":candlesClosedBy(fourHour,TIMEFRAMES["240"].milliseconds,decisionTime),D:candlesClosedBy(daily,TIMEFRAMES.D.milliseconds,decisionTime)},next=oneHour[index+1];if(history["240"].length<55||history.D.length<55||!next)continue;const spreadPct=Math.max(0,valueAt(spreadSeries,decisionTime,defaultSpreadPct)),fundingRate=valueAt(fundingSeries,decisionTime,0);const result=analyzeAt({symbol,history,price:decision.close,spreadPct,fundingRate,instrument});let btcSignal=null;if(symbol!=="PF_XBTUSD"&&btcCandlesByTimeframe){const b1=btcCandlesByTimeframe["60"]||[],b4=btcCandlesByTimeframe["240"]||[],bd=btcCandlesByTimeframe.D||[];const bh={"60":candlesClosedBy(b1,TIMEFRAMES["60"].milliseconds,decisionTime),"240":candlesClosedBy(b4,TIMEFRAMES["240"].milliseconds,decisionTime),D:candlesClosedBy(bd,TIMEFRAMES.D.milliseconds,decisionTime)};if(bh["60"].length>=55&&bh["240"].length>=55&&bh.D.length>=55)btcSignal=analyzeAt({symbol:"PF_XBTUSD",history:bh,price:bh["60"].at(-1).close,spreadPct:.04,fundingRate:0,instrument:btcInstrument});}
const gate=passes85TradeGate(result,{symbol,btcSignal});if(!gate.eligible)continue;const direction=result.status==="LONG"?1:-1,entry=Number(next.open),stop=Number(result.plan.stop),target1=Number(result.plan.target1),target2=Number(result.plan.target2),risk=Math.abs(entry-stop);if(!(risk>0)||![entry,stop,target1,target2].every(Number.isFinite))continue;if(direction===1&&!(stop<entry&&target1>entry&&target2>entry))continue;if(direction===-1&&!(stop>entry&&target1<entry&&target2<entry))continue;const evaluated=evaluateTradeWindow({candles:oneHour,startIndex:index+1,direction,entry,stop,target1,target2}),exit=oneHour[evaluated.exitIndex],feeSpreadReturn=(takerFeePct*2+spreadPct)/100,feeSpreadCostR=feeSpreadReturn/(risk/entry),fundingReturn=direction*fundingBetween(fundingSeries,next.start,exit.start),fundingCostR=fundingReturn/(risk/entry),netR=evaluated.grossR-feeSpreadCostR-fundingCostR;trades.push({symbol,direction:result.status,decisionTime,entryTime:next.start,entryPrice:entry,exitTime:exit.start,outcome:evaluated.outcome,target1Hit:evaluated.target1Hit,target2Hit:evaluated.target2Hit,grossR:evaluated.grossR,netR,feeSpreadCostR,fundingCostR,score:result.score,confidence:result.confidence,setupConfidence:result.setupConfidence,executionScore:result.executionScore,tradeQuality:result.tradeQuality,setupType:result.plan.type,stop,target1,target2});index=evaluated.exitIndex;}return{symbol,filter:{minScore:BACKTEST_MIN_SCORE,qualities:[...BACKTEST_QUALITIES],strictAltcoinGates:true,btcRegimeFilter:true},trades,summary:calculateSummary(trades)};}
export function combineBacktests(results){const trades=results.flatMap(r=>r.trades).sort((a,b)=>a.entryTime-b.entryTime);return{filter:{minScore:BACKTEST_MIN_SCORE,qualities:[...BACKTEST_QUALITIES],strictAltcoinGates:true,btcRegimeFilter:true},trades,summary:calculateSummary(trades)};}
