import { CRYPTO_CATEGORIES, MARKET_LIMITS, REST_BASE, STORAGE_KEYS, TIMEFRAMES, WS_URL } from "./constants.js";
const pause=(ms)=>new Promise(r=>setTimeout(r,ms));
export function displayBase(base){return String(base||"").toUpperCase()==="XBT"?"BTC":String(base||"").toUpperCase();}
function quantityStep(p){const d=Math.max(0,Math.min(12,Number(p)||0));return Number((10**-d).toFixed(d));}
function eeaRetailSchedule(i){return i?.marginSchedules?.europa?.retail||i?.marginSchedules?.europa_crypto?.retail||[];}
export function normalizeInstrument(i={}){const s=eeaRetailSchedule(i),im=Number(s[0]?.initialMargin),lev=im>0?Math.floor(1/im+1e-9):0,base=displayBase(i.base),qtyStep=quantityStep(i.contractValueTradePrecision),tradeable=i.type==="flexible_futures"&&String(i.symbol||"").startsWith("PF_")&&i.quote==="USD"&&i.tradeable===true&&i.isExpired!==true;return{symbol:String(i.symbol||""),base,apiBase:String(i.base||""),quote:"USD",label:`${base}/USD Perp`,category:String(i.category||"Onbekend"),tickSize:Number(i.tickSize),contractSize:Number(i.contractSize)||1,quantityPrecision:Number(i.contractValueTradePrecision)||0,qtyStep,minQty:qtyStep,maxPositionSize:Number(i.maxPositionSize),initialMargin:im,maxLeverage:Math.max(0,Math.min(10,lev)),tradeable,postOnly:i.postOnly===true,suspended:false,eeaEligible:s.length>0};}
export function filterCryptoPerpetuals(a=[]){return a.map(normalizeInstrument).filter(m=>m.tradeable&&m.eeaEligible&&m.maxLeverage>0&&CRYPTO_CATEGORIES.has(m.category));}
function derivedRelativeFunding(r,p){const a=Number(r),i=Number(p);return Number.isFinite(a)&&i>0?a/i:0;}
export function normalizeTicker(t={},receivedAt=Date.now()){const indexPrice=Number(t.indexPrice??t.index),markPrice=Number(t.markPrice),lastPrice=Number(t.last??t.lastPrice),rf=Number(t.relative_funding_rate),rp=Number(t.relative_funding_rate_prediction),premium=Number(t.premium);return{symbol:String(t.symbol??t.product_id??""),lastPrice,bid:Number(t.bid),ask:Number(t.ask),bidSize:Number(t.bidSize??t.bid_size),askSize:Number(t.askSize??t.ask_size),markPrice,indexPrice,change24h:Number(t.change24h??t.change)||0,volume24h:Number(t.vol24h??t.volume)||0,volumeQuote:Number(t.volumeQuote)||0,openInterest:Number(t.openInterest)||0,fundingRate:Number.isFinite(rf)?rf:derivedRelativeFunding(t.fundingRate,indexPrice),fundingRatePrediction:Number.isFinite(rp)?rp:derivedRelativeFunding(t.fundingRatePrediction,indexPrice),premiumPct:Number.isFinite(premium)?premium:indexPrice>0&&markPrice>0?((markPrice-indexPrice)/indexPrice)*100:NaN,suspended:t.suspended===true,postOnly:t.postOnly===true||t.post_only===true,serverTime:Number(t.time)||Date.parse(t.lastTime)||receivedAt,receivedAt};}
export function rankTopMarkets(markets,tickers,limit=MARKET_LIMITS.topMarkets){return markets.filter(m=>m.tradeable&&!tickers.get(m.symbol)?.suspended).sort((l,r)=>{const a=tickers.get(l.symbol)||{},b=tickers.get(r.symbol)||{};return(Number(b.volumeQuote)||0)-(Number(a.volumeQuote)||0)||(Number(b.openInterest)||0)-(Number(a.openInterest)||0)||l.symbol.localeCompare(r.symbol);}).slice(0,limit);}
export function normalizeCandle(r={}){return{start:Number(r.time),open:Number(r.open),high:Number(r.high),low:Number(r.low),close:Number(r.close),volume:Number(r.volume)};}
export function normalizeAnalytics(p={}){const ts=p?.result?.timestamp||[],d=p?.result?.data||{},s=d.relativeRate||d.rate||d,close=v=>Array.isArray(v)?Number(v[3]??v.at(-1)):Number(v);return ts.map((t,i)=>({start:Number(t)<1e12?Number(t)*1000:Number(t),value:close(s[i])})).filter(r=>Number.isFinite(r.start)&&Number.isFinite(r.value));}
export function normalizeSpreadAnalytics(p={}){const ts=p?.result?.timestamp||[],b=p?.result?.data?.bid?.best_price||[],a=p?.result?.data?.ask?.best_price||[];return ts.map((t,i)=>{const bid=Number(b[i]),ask=Number(a[i]),mid=(bid+ask)/2,start=Number(t)<1e12?Number(t)*1000:Number(t);return{start,value:mid>0?((ask-bid)/mid)*100:NaN};}).filter(r=>Number.isFinite(r.start)&&Number.isFinite(r.value)&&r.value>=0);}
function dedupeRows(rows){return[...new Map(rows.filter(r=>Number.isFinite(Number(r.start))).map(r=>[Number(r.start),r])).values()].sort((a,b)=>a.start-b.start);}
export class KrakenClient{
 constructor({timeout=20_000,restBase=REST_BASE,WebSocketImpl=globalThis.WebSocket}={}){this.timeout=timeout;this.restBase=restBase;this.WebSocketImpl=WebSocketImpl;this.socket=null;this.reconnectTimer=null;this.reconnectAttempt=0;this.closedIntentionally=false;this.currentSymbols=[];this.connectionGeneration=0;this.historyCache=new Map();}
 async request(path,parameters={},options={}){const timeout=Number(options.timeout)||this.timeout,retries=Math.max(0,Number(options.retries)||0),retryDelay=Math.max(0,Number(options.retryDelay)||700);let attempt=0;while(true){const url=new URL(`${this.restBase}${path}`,globalThis.location?.origin||"http://localhost");Object.entries(parameters).forEach(([k,v])=>{if(v!==undefined&&v!==null&&v!=="")url.searchParams.set(k,String(v));});const c=new AbortController(),timer=setTimeout(()=>c.abort(),timeout);try{const res=await fetch(url,{headers:{accept:"application/json"},signal:c.signal});if(!res.ok)throw new Error(`Kraken gaf HTTP ${res.status}`);return await res.json();}catch(e){const n=e.name==="AbortError"?new Error("Kraken reageerde niet op tijd"):e;if(attempt>=retries)throw n;attempt++;await pause(retryDelay*attempt);}finally{clearTimeout(timer);}}}
 async getInstruments(){const p=await this.request("/instruments");if(p.result!=="success")throw new Error("Kraken-instrumenten konden niet worden geladen");return filterCryptoPerpetuals(p.instruments||[]);}
 async getTickers(){const p=await this.request("/tickers");if(p.result!=="success")throw new Error("Kraken-tickers konden niet worden geladen");const at=Date.now();return(p.tickers||[]).map(t=>normalizeTicker(t,at));}
 async getCandles(symbol,interval,count=MARKET_LIMITS.scanHistory,extra={},options={}){const resolution=TIMEFRAMES[interval]?.resolution;if(!resolution)throw new Error("Ongeldig candle-timeframe");const p=await this.request(`/charts/${encodeURIComponent(symbol)}/${resolution}`,{...(count===null?{}:{count}),...extra},options);return(p.candles||[]).map(normalizeCandle).sort((a,b)=>a.start-b.start);}
 async getHistory(symbol,interval,days,{timeout=25_000,retries=1,cacheTtl=10*60*1000,chunkDays,onProgress}={}){const key=`history:${symbol}:${interval}:${days}`,cached=this.historyCache.get(key);if(cached&&Date.now()-cached.savedAt<cacheTtl){onProgress?.(1,1,true);return cached.rows;}const end=Math.floor(Date.now()/1000),start=end-days*86400;const defaults={"60":10,"240":30,D:90},span=Math.max(1,Number(chunkDays)||defaults[interval]||14);const chunks=[];for(let from=start;from<end;from+=span*86400)chunks.push({from,to:Math.min(end,from+span*86400)});const rows=[];for(let i=0;i<chunks.length;i++){const chunk=chunks[i];const part=await this.getCandles(symbol,interval,null,chunk,{timeout,retries});rows.push(...part);onProgress?.(i+1,chunks.length,false);if(i<chunks.length-1)await pause(120);}const merged=dedupeRows(rows).filter(r=>r.start>=start*1000&&r.start<=end*1000);if(!merged.length)throw new Error(`Kraken leverde geen ${interval}-historiek`);this.historyCache.set(key,{savedAt:Date.now(),rows:merged});return merged;}
 async getFundingHistory(symbol,days=95,{timeout=35_000,retries=1,cacheTtl=10*60*1000}={}){const key=`funding:${symbol}:${days}`,c=this.historyCache.get(key);if(c&&Date.now()-c.savedAt<cacheTtl)return c.rows;const to=Math.floor(Date.now()/1000),since=to-days*86400,rows=normalizeAnalytics(await this.request(`/funding/${encodeURIComponent(symbol)}`,{since,to,interval:3600},{timeout,retries}));this.historyCache.set(key,{savedAt:Date.now(),rows});return rows;}
 async getSpreadHistory(symbol,days=95,{timeout=35_000,retries=1,cacheTtl=10*60*1000}={}){const key=`spread:${symbol}:${days}`,c=this.historyCache.get(key);if(c&&Date.now()-c.savedAt<cacheTtl)return c.rows;const to=Math.floor(Date.now()/1000),since=to-days*86400,rows=normalizeSpreadAnalytics(await this.request(`/spreads/${encodeURIComponent(symbol)}`,{since,to,interval:3600},{timeout,retries}));this.historyCache.set(key,{savedAt:Date.now(),rows});return rows;}
 connectPublic(symbols,h={}){this.disconnect();const g=++this.connectionGeneration;this.currentSymbols=[...new Set(symbols)].filter(Boolean);this.closedIntentionally=false;const open=()=>{if(g!==this.connectionGeneration||this.closedIntentionally)return;h.onStatus?.("connecting");this.socket=new this.WebSocketImpl(WS_URL);this.socket.addEventListener("open",()=>{if(g!==this.connectionGeneration)return;this.reconnectAttempt=0;h.onStatus?.("live");this.socket.send(JSON.stringify({event:"subscribe",feed:"ticker",product_ids:this.currentSymbols}));this.socket.send(JSON.stringify({event:"subscribe",feed:"heartbeat"}));});this.socket.addEventListener("message",e=>{if(g!==this.connectionGeneration)return;let m;try{m=JSON.parse(e.data);}catch{return;}if(m.feed==="heartbeat")h.onHeartbeat?.(Number(m.time)||Date.now());if(m.feed==="ticker"&&m.product_id)h.onTicker?.(m.product_id,normalizeTicker(m,Date.now()));});this.socket.addEventListener("close",()=>{if(g!==this.connectionGeneration)return;h.onStatus?.("offline");if(this.closedIntentionally)return;const d=Math.min(30_000,1_000*2**this.reconnectAttempt);this.reconnectAttempt++;clearTimeout(this.reconnectTimer);this.reconnectTimer=setTimeout(open,d);});this.socket.addEventListener("error",()=>h.onStatus?.("offline"));};open();}
 disconnect(){this.closedIntentionally=true;this.connectionGeneration++;clearTimeout(this.reconnectTimer);if(this.socket){this.socket.onclose=null;this.socket.close();this.socket=null;}}
}
export function saveSnapshot(s){try{const e=Object.entries(s.candles||{}).sort(([,a],[,b])=>(Number(b?.savedAt)||0)-(Number(a?.savedAt)||0)).slice(0,MARKET_LIMITS.cachedMarkets);localStorage.setItem(STORAGE_KEYS.snapshot,JSON.stringify({...s,candles:Object.fromEntries(e)}));}catch{}}
export function loadSnapshot(){try{const p=JSON.parse(localStorage.getItem(STORAGE_KEYS.snapshot));return p?.version===2&&p?.savedAt&&p?.candles?p:null;}catch{return null;}}
export async function runPool(tasks,concurrency=4,onProgress){let cursor=0,completed=0;const workers=Array.from({length:Math.min(concurrency,tasks.length)},async()=>{while(cursor<tasks.length){const i=cursor++;await tasks[i]();completed++;onProgress?.(completed,tasks.length);if(completed%12===0)await pause(40);}});await Promise.all(workers);}
